### ISSUE TITLE
VOC2012 and Pascal-5i

### ISSUE THREAD

**Issue by Fenganzhuliang** [Yang-Bob/PMMs#12]
Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks!
![image](https://user-images.githubusercontent.com/42239939/97778753-4162f680-1bb4-11eb-82d4-f30a86b9fe93.png)

**Comment by Fenganzhuliang** [comment]
I have used the github project Pascal-5 to run the annotation results, as shown below, but how do they apply to the project to form the splitX_train.txt and splitX_val.txt format?
![image](https://user-images.githubusercontent.com/42239939/97779352-678a9580-1bb8-11eb-85e3-57dfd401c642.png)

**Comment by Yang-Bob** [comment]
Hi,
The Pascal-5i dataset consists of the Pascal VOC 2012 dataset with extra annotations from extended SDS. Have you checked your directory or data existed?
In our project, you don't need to config the data format. You can just config the data directory and follow the README to run the code.

**Comment by Fenganzhuliang** [comment]
> Hi,
> The Pascal-5i dataset consists of the Pascal VOC 2012 dataset with extra annotations from extended SDS. Have you checked your directory or data existed?
> In our project, you don't need to config the data format. You can just config the data directory and follow the README to run the code.

OK, Thank you very much! I will check my code and data set more carefully!

**Comment by Fenganzhuliang** [comment]
> Hi,
> The Pascal-5i dataset consists of the Pascal VOC 2012 dataset with extra annotations from extended SDS. Have you checked your directory or data existed?
> In our project, you don't need to config the data format. You can just config the data directory and follow the README to run the code.

Great, I solved my problem. The reason is that the mask folder in voc2012——SegmentationClassAug. This should be downloaded from the pascal voc official website. The voc2012 data set I originally used is from my friend, and the mask folder inside is SegmentationClass, there may be some image masks missing. Thank you again!

**Comment by cql980603** [comment]
> Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks!
> ![image](https://user-images.githubusercontent.com/42239939/97778753-4162f680-1bb4-11eb-82d4-f30a86b9fe93.png)

could you tell me where did you  finally get the Pascal 5i dataset

**Comment by Fenganzhuliang** [comment]
I used the VOC2012 data set directly, and then downloaded the enhanced version named SegmentationClassAug to replace the original SegmentationClass; the others remain unchanged. 
The VOC2012 catalog diagram is as follows, and I will show you the SegmentationClassAug compressed package. If you use Baidu network disk, please see the link:&nbsp;
https://pan.baidu.com/s/11GLWAtsfbPY221X9lcnN1w
code：xaq7&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yang-Bob/PMMs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 中午1:51
收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;;
抄送:&nbsp;"肖芳燕"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12)





  
Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks!
 
  
could you tell me where did you  finally get the Pascal 5i dataset

**Comment by cql980603** [comment]
> I used the VOC2012 data set directly, and then downloaded the enhanced version named SegmentationClassAug to replace the original SegmentationClass; the others remain unchanged. The VOC2012 catalog diagram is as follows, and I will show you the SegmentationClassAug compressed package. If you use Baidu network disk, please see the link:&nbsp; https://pan.baidu.com/s/11GLWAtsfbPY221X9lcnN1w code：xaq7&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yang-Bob/PMMs" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月11日(星期五) 中午1:51 收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;; 抄送:&nbsp;"肖芳燕"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks! could you tell me where did you finally get the Pascal 5i dataset — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your help, but the code is wrong, could you provide me with the correct code?

**Comment by Fenganzhuliang** [comment]
There is no error in the code of PMMs. If your environment is configured correctly, you can just config the dataset directory and follow the README to run the code. The author's github is also&nbsp;explains clearly. Please double check the path and environment configuration problems. Then, my torch version is different from the author's proposal. The following is my torch configuration, which can run the code smoothly. Good Luck!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yang-Bob/PMMs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 下午4:39
收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;;
抄送:&nbsp;"Fenger Xiao"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12)





  
I used the VOC2012 data set directly, and then downloaded the enhanced version named SegmentationClassAug to replace the original SegmentationClass; the others remain unchanged. The VOC2012 catalog diagram is as follows, and I will show you the SegmentationClassAug compressed package. If you use Baidu network disk, please see the link:&nbsp; https://pan.baidu.com/s/11GLWAtsfbPY221X9lcnN1w code：xaq7&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yang-Bob/PMMs" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月11日(星期五) 中午1:51 收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;; 抄送:&nbsp;"肖芳燕"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks! could you tell me where did you finally get the Pascal 5i dataset — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Thanks for your help, but the code is wrong, could you provide me with the correct code?

**Comment by cql980603** [comment]
> There is no error in the code of PMMs. If your environment is configured correctly, you can just config the dataset directory and follow the README to run the code. The author's github is also&nbsp;explains clearly. Please double check the path and environment configuration problems. Then, my torch version is different from the author's proposal. The following is my torch configuration, which can run the code smoothly. Good Luck!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yang-Bob/PMMs" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月11日(星期五) 下午4:39 收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;; 抄送:&nbsp;"Fenger Xiao"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) I used the VOC2012 data set directly, and then downloaded the enhanced version named SegmentationClassAug to replace the original SegmentationClass; the others remain unchanged. The VOC2012 catalog diagram is as follows, and I will show you the SegmentationClassAug compressed package. If you use Baidu network disk, please see the link:&nbsp; https://pan.baidu.com/s/11GLWAtsfbPY221X9lcnN1w code：xaq7&nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yang-Bob/PMMs" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月11日(星期五) 中午1:51 收件人:&nbsp;"Yang-Bob/PMMs"<PMMs@noreply.github.com&gt;; 抄送:&nbsp;"肖芳燕"<2582728795@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks! could you tell me where did you finally get the Pascal 5i dataset — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks for your help, but the code is wrong, could you provide me with the correct code? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

OH！what I mean is that the code for Baidu network disk is wrong. Not the source code.

**Comment by Fenganzhuliang** [comment]
> > There is no error in the code of PMMs. If your environment is configured correctly, you can just config the dataset directory and follow the README to run the code. The author's github is also explains clearly. Please double check the path and environment configuration problems. Then, my torch version is different from the author's proposal. The following is my torch configuration, which can run the code smoothly. Good Luck!
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Yang-Bob/PMMs" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年12月11日(星期五) 下午4:39 收件人: "Yang-Bob/PMMs"<[PMMs@noreply.github.com](mailto:PMMs@noreply.github.com)>; 抄送: "Fenger Xiao"<[2582728795@qq.com](mailto:2582728795@qq.com)>;"State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题: Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) I used the VOC2012 data set directly, and then downloaded the enhanced version named SegmentationClassAug to replace the original SegmentationClass; the others remain unchanged. The VOC2012 catalog diagram is as follows, and I will show you the SegmentationClassAug compressed package. If you use Baidu network disk, please see the link:  https://pan.baidu.com/s/11GLWAtsfbPY221X9lcnN1w code：xaq7  … ------------------ 原始邮件 ------------------ 发件人: "Yang-Bob/PMMs" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年12月11日(星期五) 中午1:51 收件人: "Yang-Bob/PMMs"<[PMMs@noreply.github.com](mailto:PMMs@noreply.github.com)>; 抄送: "肖芳燕"<[2582728795@qq.com](mailto:2582728795@qq.com)>;"State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题: Re: [Yang-Bob/PMMs] VOC2012 and Pascal-5i (#12) Hello! I'm sorry I am a newbie in deep learning, I want to ask how to get the Dataset Pascal-5i, I used VOC2012 directly, but there will be some label and picture mismatch problems. Thanks! could you tell me where did you finally get the Pascal 5i dataset — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks for your help, but the code is wrong, could you provide me with the correct code? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> OH！what I mean is that the code for Baidu network disk is wrong. Not the source code.

The password is xaq7, nothing wrong.^_^
