### ISSUE TITLE
 the resume question 

### ISSUE THREAD

**Issue by cql980603** [Yang-Bob/PMMs#16]
The training phase is very time-cosuming,  if the training phase is stopped in the middle time, could we resume from the last saved model?

**Comment by Yang-Bob** [comment]
Yes of course.  You can pass the argument of `start_count` of the last model you saved. The model will load the last saved model parameters and restart trained from `start_count`.
https://github.com/Yang-Bob/PMMs/blob/a8a0cacf1cae7414d6e3c1caabb0463246d837ab/train.py#L36

**Comment by cql980603** [comment]
> Yes of course. You can pass the argument of `start_count` of the last model you saved. The model will load the last saved model parameters and restart trained from `start_count`.
> https://github.com/Yang-Bob/PMMs/blob/a8a0cacf1cae7414d6e3c1caabb0463246d837ab/train.py#L36

![image](https://user-images.githubusercontent.com/46946418/100178484-e69c9080-2f0e-11eb-8166-8910e3ce23c6.png)
Thanks for your help, I have done as you mentioned, but  an error emerged, you may need to modify the sourced code

**Comment by Yang-Bob** [comment]
I have revised it. You can add `args.restore_step = args.start_count` before `restore(args, model)`

**Comment by cql980603** [comment]
> Thanks for your reminder. I have revised it. You can add `args.restore_step = args.start_count` before `restore(args, model)`

Thanks for your help. I have fixed it.
