### ISSUE TITLE
Found error in computing performance (iou)

### ISSUE THREAD

**Issue by juhongm999** [Yang-Bob/PMMs#17]
Hello,
I found an error in your evaluation code (in function "update_evl" of NoteEvaluation.py).

Given N sample episodes, your code computes average IoU as follows:
(tp_1 + tp_2 + ... + tp_N) / (uni_1 + uni_2 + ... + uni_N)
where uni = tp + fp + fn (union) and tp (intersection)

I believe correct way of measuring IoU is following:
1/N * sum_{i=1}^{N} (tp_i) / (uni_i)

Is there anything that I'm missing from your code?
If I'm correct how would the resulting mIoU change on PASCAL-5i?

Thank you.

**Comment by juhongm999** [comment]
I've searched codes of other recent state of the art methods (PFENet, CANet, SG-one).

I found that they also adopt the same way when computing IoU:
PFENet: https://github.com/Jia-Research-Lab/PFENet/blob/master/train.py (line 422-423)
CANet: https://github.com/icoz69/CaNet/blob/master/train.py (line 244-245)
SG-one: https://github.com/xiaomengyc/SG-One/blob/master/test_frame_all.py (line 136-138)

I think this won't be a huge problem in terms of fairness in evaluation as long as all the past and future methods adopt the same way of measuring IoU. However, I still believe "episode-wise" IoU is correct way of measuring average IoU because two different computations output different average IoU values. 

Or there may be something that I'm missing in the task of few-shot semantic segmentation.
Please let me know if so, and leave comments if you have any.
Thank you.

**Comment by Yang-Bob** [comment]
Hi,

There is NO error in computing performance since it is evaluated under mIoU.

MIoU is defined as the mean IoUs of all categories. For each category, the IoU is calculated by IoU = TP/(TP+FP+FN), where TP, FP and FN respectively denote the number of true positive, false positive and false negative pixels of the predicted segmentation mask of each category. NOTE that mIoU mainly denots the mean of class-wise intersection over union:

1. Calculate the IoU of each category;
2. Calculate the mIoU by averaging IoU of each category

Under this metric(mIoU), the method of few-shot semantic segmentation is evaluated.

In addition, mIoU is also used in substantial semantic segmentation works, e.g., FCN, Deeplab, PSPNet etc.  If you're interested, you can refer to these papers or source codes.

I hope this will help you!

Sincerely,
Bob

**Comment by juhongm999** [comment]
Thanks for the quick reply but I meant **average IoU of each class**, not mIoU.

**Comment by juhongm999** [comment]
Just in case, let me make things clear.
Given N episodes within ONE object class, model outputs N predictions.
For brevity, say I (= tp) and U (= tp + fp + fn) detones intersection and union respectively.
I believe correct way of computing average IoU of for some class c is defined as:

	IoU_{c} = 1/N * (I_1 / U_1 + I_2 / U_2 + ... + I_N / U_N)			(1)

To compute mIoU (class-wise mean), you take another mean over average IoU of each class

	mIoU = 1/C (IoU_{1} + IoU_{2} + ... + IoU_{C})				(2)

But the code computes IoU of some class c as:

	IoU_{c} = (I_1 + I_2 + ... + I_N) / (U_1 + U_2 + ... + U_N)		(3)

Note that Equations (1) and (3) output different values given the same set of input values.

**Comment by Yang-Bob** [comment]
I get what you mean and I think there are 2 points need to deliberate.

1. What's your motivation of the metric you proposed? Few-shot semantic segmentation or semantic segmentation are pixel-wised classification.  The metric you proposed may lead to different weight of pixels from different images. For example, 1 pixel foreground vs. 100 pixels foreground. If the model misclassifies one pixel of former one, the performance will drop to about 50%, while for the latter one, the performance will be almost unchanged. However, for a pixel-wised classification task, each pixel should have a same effect on the performance. Besides, most of the works of few-shot semantic segmentation or semantic segmentation are evaluated under mIoU.
2. The defination of IoU is IoU = TP/(TP+FP+FN). Eq.1 may be average IoU as AIoU_{c} and Eq.2 may be mAIoU NOT mIoU. Eq.3 is the defination of IoU.

At last, I think you should refer to the Evaluation of above papers. If you insist, you can try the metric you proposed.

**Comment by juhongm999** [comment]
Thanks for your detailed comments.
Your explanation somewhat cleared my doubts while I'm still curious how such way of computing IoU became a standard convention in segmentation.
Any recommended references would be grateful.
I'm closing the issue and thanks for active discussion.

**Comment by Yang-Bob** [comment]
Thanks for your meticulous deliberation and comment! 
Hope to communicate with you in the future.
