### ISSUE TITLE
the permance  on Pascal-5i

### ISSUE THREAD

**Issue by cql980603** [Yang-Bob/PMMs#18]
![image](https://user-images.githubusercontent.com/46946418/101857245-089a4200-3ba2-11eb-940d-2fc5c2ffd9c4.png)
I'm trying to reproduce results on Pascal-5i with the pred-trained weights that you provided, but the results I obtain stand is  below the ones announced in the paper.

**Comment by Yang-Bob** [comment]
Hi,
You should keep all of the default settings in this code as the e-mail replied.
