### ISSUE TITLE
PASCAL VOC data_list

### ISSUE THREAD

**Issue by LiheYoung** [Yang-Bob/PMMs#7]
Hi, thanks for sharing your work!

It seems that you train and test in VOC using ids from your 'data_list' directory. However, if ids are generated from the train+aug set from VOC and SBD, there should be more ids than those in 'data_list' directory(for example, in my experiment, there are 8829 images containing objects from classes excluding split_0). So would you mind describing the process of generating those ids in each split?

**Comment by Yang-Bob** [comment]
Hi, the data_list file is also used in CANet(our baseline). For fair comparison, we use this file to get the image.

**Comment by LiheYoung** [comment]
Thanks for explanation!
