### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by BoomFan** [Yang-Bob/PMMs#8]
Hi Bob,

Do you provide any pre-trained weights so that we can run as a demo code?

Could you provide a link to download such pre-trained weights?

Thanks!

**Comment by Yang-Bob** [comment]
Hi, you can get the pretrained RPMMs weights in [https://github.com/ECCV20/PMMs/tree/master/snapshots/FRPMMs](https://github.com/ECCV20/PMMs/tree/master/snapshots/FRPMMs).
After downloading the pretrained weights, you can put the `snapshots/` folder under the current directory or modify related config code.

**Comment by BoomFan** [comment]
Great! Thanks Bob!

I downloaded the dataset and run the `python3 test_frame.py` command. It works!

Now I change the `val_dataloader = val_loader(args,k_shot=1)` to `val_dataloader = val_loader(args,k_shot=5)`, and I run `python3 test_frame.py` again. I got this error: `RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 3 7 7, but got 5-dimensional input of size [1, 5, 3, 481, 481] instead`

Could you help to see if you can reproduce the same error, please?

**Comment by BoomFan** [comment]
Oh, I got it, I changed `from oneshot import *` to `from networks import *`. Is that a proper fix?

**Comment by Yang-Bob** [comment]
Oh, yeah. I have fixed it. Thanks for your reminder!
